name: Build BSR

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
    runs-on: ${{ matrix.os }}

    steps:
    - name: Install Dependencies (Linux)
      run: sudo apt-get install -y build-essential gfortran liblapack-dev libblas-dev openmpi-bin openmpi-common libopenmpi-dev libscalapack-openmpi-dev
      if: matrix.os == 'ubuntu-latest'
    - name: Install Dependencies (macOS)
      run: brew install gcc open-mpi
      if: matrix.os == 'macos-latest'

    - name: Get Sources
      uses: actions/checkout@v2

    - name: Setup CMake
      run: |
        mkdir "${{ runner.workspace }}/build"
        cd "${{ runner.workspace }}/build"
        cmake $GITHUB_WORKSPACE/src
      shell: bash

    - name: Build
      run: cmake --build .
      working-directory: ${{ runner.workspace }}/build
    - name: Test
      run: ctest -V
      working-directory: ${{ runner.workspace }}/build
